[package]
name = "genmake"
version = "0.5.0"
authors = ["Michał Kallas"]
description = "genmake is a command line tool that generates a Makefile based on the files in your directory"
homepage = "https://github.com/kallazz/genmake"
repository = "https://github.com/kallazz/genmake"
keywords = ["makefile", "generate"]
categories = ["command-line-utilities", "development-tools"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.23", features = ["derive"] }
